{
 "title": "Bootcamp",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Select Site",
    "query": "oslo,hannover,nuremberg,marseille,houston,sao_paulo,kuala_lumpur,chicago,rotterdam,london"
   },
   {
    "name": "production_line",
    "label": "Production Line",
    "query": {
     "query": "assets{parentExternalIds=['${site}_production']}"
    }
   },
   {
    "name": "machine",
    "label": "Machine",
    "query": {
     "query": "assets{parentIds=[$production_line]}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Performance for $production_line",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='performance'},assetSubtreeIds=[{id=$production_line}]})",
     "tab": "Custom"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='performance'},assetSubtreeIds=[{id=$production_line}]})",
     "label": "performance_production_line",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='performance'},assetSubtreeIds=[{id=$machine}]}",
     "label": "performance_machine",
     "tab": "Custom"
    },
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='status'},assetSubtreeIds=[{id=$machine}]}",
     "label": "status",
     "tab": "Custom"
    }
   ]
  },
  {
   "title": "Availability ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='availability'},assetSubtreeIds=[{id=$production_line}]})",
     "tab": "Custom"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='availability'},assetSubtreeIds=[{id=$production_line}]})",
     "label": "availability_production_line",
     "tab": "Custom"
    },
    {
     "aggregation": "stepInterpolation",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='planned_status'},assetSubtreeIds=[{id=$machine}]}",
     "label": "planned_status",
     "tab": "Custom"
    },
    {
     "aggregation": "stepInterpolation",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='status'},assetSubtreeIds=[{id=$machine}]}",
     "label": "status",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='availability'},assetSubtreeIds=[{id=$machine}]}",
     "label": "availability_machine",
     "tab": "Custom"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='quality'},assetSubtreeIds=[{id=$production_line}]})",
     "tab": "Custom"
    }
   ]
  },
  {
   "title": "Quality ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 16 },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='quality'},assetSubtreeIds=[{id=$production_line}]})",
     "label": "quality_production_line",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='count'},assetSubtreeIds=[{id=$machine}]}",
     "label": "count",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='good'},assetSubtreeIds=[{id=$machine}]}",
     "label": "good",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='quality'},assetSubtreeIds=[{id=$machine}]}",
     "label": "quality_production_line",
     "tab": "Custom"
    }
   ]
  },
  {
   "title": "OOE for $production_line",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='oee'},assetSubtreeIds=[{id=$production_line}]})",
     "tab": "Custom"
    }
   ]
  },
  {
   "title": "Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 24 },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='oee'},assetSubtreeIds=[{id=$production_line}]})",
     "label": "oee production_line: $production_line",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='oee'},assetSubtreeIds=[{id=$machine}]}",
     "label": "oee machineId: $machine",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "tab": "Asset"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='availability'},assetSubtreeIds=[{id=$machine}]}",
     "label": "Availability",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='performance'},assetSubtreeIds=[{id=$machine}]}",
     "label": "Performance ",
     "tab": "Custom"
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='quality'},assetSubtreeIds=[{id=$machine}]}",
     "label": "Quality",
     "tab": "Custom"
    }
   ]
  }
 ]
}